name: riverpodproject
description: a project testing riverpod as  a state management solution



publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # equatable: ^2.0.5
  json_serializable: ^6.5.1
  build_runner: ^2.3.0
  flutter_riverpod: ^2.0.2
  go_router: ^5.1.0
  url_launcher: "^6.1.3"
  uni_links: "^0.5.1"
  dio: ^4.0.6
  retrofit: ^3.3.1
  retrofit_generator: ^4.2.0
  mocktail_image_network: ^0.3.1
  flutter_easyloading: ^3.0.5
  another_flushbar: ^1.12.29
  bodsquare_sdk:
    path: packages/bodsquare_sdk


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - data/
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
